nfactor: 60
out-dir: '/home/t.cri.yliang/labshare/ASE/peer_factor_for_trc_refactored'
tissue: 'Whole_Blood'
covariate: '/gpfs/data/gtex-group/v8/59349/gtex/exchange/GTEx_phs000424/exchange/analysis_releases/GTEx_Analysis_2017-06-05_v8/eqtl/GTEx_Analysis_v8_eQTL_covariates/Whole_Blood.v8.covariates.txt'
