data:
  genotype: '/scratch/t.cri.yliang/mixqtl-pipeline-results/simulation-multi/genotype__SelectedGenes.size_100.{m}.rds'
  readcount: '/scratch/t.cri.yliang/mixqtl-pipeline-results/simulation-multi/readcount__samplesize100_x_theta5e-6--SelectedGenes.size_100.1.rds'
  M_from: 1
  M_to: 2
  name: 'test'
finemapper: 'mixfine'
