tissue: 'Whole_Blood'
method: 'mixfine'
covariate: '/gpfs/data/im-lab/nas40t2/yanyul/GTExV8-mixqtl/mixqtl-pipeline-results/gtex_v8-preprocess/peer/Whole_Blood/covariate-combined.txt'
# genelist: 'data/gene_list_whole_blood_with_qc.txt'
expression: '/gpfs/data/im-lab/nas40t2/yanyul/GTExV8-mixqtl/mixqtl-pipeline-results/gtex_v8-preprocess/expression/merge-Whole_Blood.rds'
genotype: '/gpfs/data/im-lab/nas40t2/yanyul/GTExV8-mixqtl/mixqtl-pipeline-results/gtex_v8-preprocess/genotype/{gene}.txt.gz'
outdir: '/scratch/t.cri.yliang/mixqtl-pipeline-results/gtex_v8-results/mixfine'
