#PBS -S /bin/bash
#PBS -l walltime=12:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -e logs/prep_gene--${MYID}.err
#PBS -o logs/prep_gene--${MYID}.out


source ~/.bash_profile
source ~/.bashrc
cd /gpfs/data/im-lab/nas40t2/yanyul/GitHub/mixqtl-pipeline/pipeline/gtex_v8 
conda activate mixqtl

snakemake -s mixfine.snmk --configfile ../../qsub/gtex_v8/mixfine/config.mixfine.yaml all_input -p --nolock --config gene_list=$GENELIST >> ../../qsub/gtex_v8/mixfine/logs/prep_gene--$MYID.log 2>&1
