tissue: 'Whole_Blood'
method: 'mixpred'
covariate: '/scratch/t.cri.yliang/mixqtl-pipeline-results/gtex_v8-preprocess/peer/Whole_Blood/covariate-combined.txt'
expression: '/scratch/t.cri.yliang/mixqtl-pipeline-results/gtex_v8-preprocess/expression/merge-Whole_Blood.rds'
genotype: '/scratch/t.cri.yliang/mixqtl-pipeline-results/gtex_v8-preprocess/genotype/{gene}.txt.gz'
indiv_partition: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/mixqtl-pipeline/misc_data/prediction_partition_whole_blood.partition_2.txt' 
indiv_partition_name: 'gtex_v8_whole_blood_partition_2'
outdir: '/scratch/t.cri.yliang/mixqtl-pipeline-results/gtex_v8-results/mixpred-partition-p2'

