tissue: 'Whole_Blood'
name: 'result-mixqtl_low_count_impute_inv_norm'
gene_list: '../../misc_data/gtex-v8-genes-low-expr_gene_list.txt'
gene_file: '/scratch/t.cri.yliang/mixqtl-pipeline-results/gtex_v8-results/mixqtl-low_count_genes_impute_inv_norm/{{tissue}}/{{name}}.{gene}.txt.gz'
outdir: '/scratch/t.cri.yliang/mixqtl-pipeline-results/gtex_v8-results/postprocess-mixqtl'
