#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb
#PBS -e run.err
#PBS -o run.out


source ~/.bash_profile
source ~/.bashrc
cd /gpfs/data/im-lab/nas40t2/yanyul/GitHub/mixqtl-pipeline/pipeline/gtex_v8
conda activate mixqtl

snakemake -s postprocess_merge.snmk --configfile ../../qsub/gtex_v8/postprocess_merge/config.yaml -p > ../../qsub/gtex_v8/postprocess_merge/run.log 2>&1

