#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb
#PBS -e run.err
#PBS -o run.out
#PBS -N wasp2matrix


source ~/.bash_profile
source ~/.bashrc
cd /gpfs/data/im-lab/nas40t2/yanyul/GitHub/mixqtl-pipeline/pipeline/gtex_v8
conda activate mixqtl 

snakemake -s wasp2matrix.snmk --configfile ../../qsub/gtex_v8/wasp2matrix/config.yaml -p > ../../qsub/gtex_v8/wasp2matrix/run.log 2>&1
