task: 'TEST'
blacklist:
  region: 'hg19_hla.bed'
  haplo-mappability: 'hg19_haplo_count_blacklist.bed'
phaser-parameter:
  mapq: 255  # minimum mapping quality of reads to use for phasing and ASE. This should be set to a value that will ensure reads are uniquely mapped. When STAR is used this number is 255, however it will differ based on the aligner.
  baseq: 10  # minimum base quality at the heterozygous SNP for a read to be used.
  paired_end: 1  # specifying that the reads come from a paired end experiment.
data:
  genotype: 'NA06986.vcf.gz'  # indexed VCF; phased; per individual but not necessary
  rnaseq: 'NA06986.2.M_111215_4.bam'  # indexed BAM; per sample
  indiv-id: 'NA06986'  # individual ID in the VCF
phaser:
  phaser: '/home/t.cri.yliang/miniconda2/envs/phaser/bin/python /home/t.cri.yliang/scratch/repo/phaser/phaser/phaser.py'
  phaser_gene_ae: '/home/t.cri.yliang/miniconda2/envs/phaser/bin/python /home/t.cri.yliang/scratch/repo/phaser/phaser/phaser_gene_ae.py'
