# target_name: 'mapped-hepg2.sign.id.LP190708'
# from_name: 'Whole_Blood-x-result_pip-mixfine'

target_list:
  path: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/mixqtl-pipeline/misc_data/{target_name}.txt.gz'
  varcol: 18
  genecol: -1
from_list:
  path: '/scratch/t.cri.yliang/mixqtl-pipeline-results/gtex_v8-results/postprocess-finemap/{from_name}.txt.gz'
  varcol: 4
  genecol: -1
outdir: '/scratch/t.cri.yliang/mixqtl-pipeline-results/gtex_v8-results/postprocess-finemap'
