#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb
#PBS -e run_${TARGET}-${FROM}.err
#PBS -o run_${TARGET}-${FROM}.out


source ~/.bash_profile
source ~/.bashrc
cd /gpfs/data/im-lab/nas40t2/yanyul/GitHub/mixqtl-pipeline/pipeline/gtex_v8/
conda activate mixqtl

snakemake -s postprocess_extract.snmk --configfile ../../qsub/gtex_v8/postprocess_extract/config.finemap.yaml --config target_name=$TARGET from_name=$FROM -p > ../../qsub/gtex_v8/postprocess_extract/run_${TARGET}-${FROM}.log 2>&1

