genotype:
  path: '/gpfs/data/im-lab/nas40t2/yanyul/GTExV8-mixqtl/mixqtl-pipeline-results/gen_geno_for_multi_snp_simulation/genotype.{gene}.gz'
  indiv-list: '/gpfs/data/im-lab/nas40t2/yanyul/GTExV8-mixqtl/mixqtl-pipeline-results/gen_geno_for_multi_snp_simulation/EUR.sample_list_in_phase3.txt'
M: 100
gene-list: 
  name: 'SelectedGenes'
  path: '/gpfs/data/im-lab/nas40t2/yanyul/GTExV8-mixqtl/mixqtl-pipeline-results/gen_geno_for_multi_snp_simulation/selected_genes.txt'
  col: 4  # index of column that contains the gene id
